title: Materi Bootcamp
subTitle: Software Engineer
author: Dimas Maryanto
jobName: Principal Software Engineer
email: software.dimas_m@icloud.com
description: >- # this means to ignore newlines until "baseurl:"
  Website ini bertujuan untuk memudahkan temen-temen untuk mempelajari 
  suatu teknologi yang berkaitan dengan Profesi IT, Programming, Tips and Trick, System Design dan lain-lain,
  Khususnya dalam Bahasa Pemogramana Java, JavaScript, TypeScript, Angular, ReactJS.
baseurl: "/bootcamp" # the subpath of your site, e.g. /blog
url: "https://www.dimas-maryanto.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
gist:
  noscript: false
permalink: /:categories/:title
plugins:
  - jekyll-gist
  - kramdown
  - rouge
  - jekyll-youtube
  
titlecase: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - docker-compose.yml
  - vendor
#   - Gemfile
  - Gemfile.lock
  - package-lock.json
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
