title: Road Map Software Engineer - 2018/2019
subTitle: Software Engineer
author: Dimas Maryanto
email: engineer.dimmaryanto93@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/bootcamp" # the subpath of your site, e.g. /blog
url: "http://www.dimas-maryanto.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dimMaryanto93
github_username:  dimMaryanto93

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
gist:
  noscript: false
permalink: /:categories/:title
plugins:
  - jekyll-gist
  - kramdown
  - rouge

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - docker-compose.yml
  - vendor
#   - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
