version: '3.6'
services:
  postgres:
    image: ${PRIVATE_REPOSITORY}postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_HOST_AUTH_METHOD
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - postgres-network
  flyway: 
    image: boxfuse/flyway
    command: -url=jdbc:postgresql://postgresql:5432/bootcamp -schemas=bootcamp -user=bootcamp -password=bootcamp -connectRetries=60 migrate
    volumes:
      - ./db/migration:/flyway/sql
    depends_on:
      - postgresql
volumes:
  pg_data: